name: Testes CodeceptJS com Appium
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Configurar Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Instalar dependências
      run: |
        npm install -g appium
        npm install

    - name: Instalar Appium
      run: |
        npm install -g appium
        appium driver install uiautomator2

    - name: Executar testes CodeceptJS
      run: |
        npx codeceptjs run --verbose

    - name: Arquivar relatórios de testes
      uses: actions/upload-artifact@v3
      with:
        name: codeceptjs-reports
        path: output

    - name: Mostrar os logs do Appium
      run: |
        tail -n 50 appium.log
